[env]
GIT_DESCRIBE = { script = ["git describe --dirty --always --tags"] }

[env.development]
WASM_PACK_FLAGS = "--dev"

[env.production]
WASM_PACK_FLAGS = "--release"

[tasks.build-wasm]
script = '''
wasm-pack build --target web --no-typescript ${WASM_PACK_FLAGS}
rm pkg/package.json pkg/README.md
'''

[tasks.dist]
script = '''
rm -rf dist
mkdir dist
cp -r pkg/* dist/
cp -r static/* dist/
'''
dependencies = ["build-wasm"]

[tasks.clean]
clear = true
script = '''
rm -rf dist pkg pkg-parallel
cargo clean
'''

[tasks.serve]
command = "devserver"
args = [
  "--path"
, "dist"
, "--header"
, "Cross-Origin-Opener-Policy=same-origin"
, "--header"
, "Cross-Origin-Embedder-Policy=require-corp"
]
dependencies = ["dist"]
watch = { ignore_pattern = "README.md" }
