[package]
name = "homotopy-core"
version = "0.1.0"
authors = ["Lukas Heidemann <lukas@heidemann.me>", "Nick Hu <me@nickhu.co.uk>"]
edition = "2018"

[dependencies]
highway = "*"
log = "*"
petgraph = "*"
serde = { features = ["derive"], version = "1.0" }
rmp-serde = { features = ["serde128"], version = "*" } # u128 support is new
thiserror = "*"

[dev-dependencies]
cargo-husky = { features = ["precommit-hook", "run-cargo-check", "run-cargo-test", "run-cargo-fmt", "run-cargo-clippy"], version = "*" }
insta = "*"
